### ISSUE TITLE
CHILD LOOP NOT GETTING IDENTIFIED CORRECTLY

### ISSUE THREAD

**Issue by nsharma-bh** [xlate/staedi#229]
I'm using the **x12/005010X222/837_loop1000_only.xml** from test/resources. Parent loops such as 1000A, 1000B, 2300, 2400 are getting identified correctly and actually prints the loop name describe in the `<loop code="">`. The same is good for child loops such as 2010AA, 2010AB. But other than those loops I'm not getting correct codes described in the loop definition itself, specifically 2310A and 2310B. 
I'm uploading the test file that I'm using along with the XML as a text file I have extended from the base 837_loop1000_only.xml

[EDI.txt](https://github.com/xlate/staedi/files/7693357/EDI.txt)
[837_loop1000_only.txt](https://github.com/xlate/staedi/files/7693420/837_loop1000_only.txt)

.

**Comment by MikeEdgar** [comment]
Thanks for the report @nsharma-bh. I'm looking into it and I think this will help solve a few issues that I've found. One issue that I see is that the order of the segments in your `<implementation>` loop 2300 is different from the order in the standard `<transaction>`. That is the cause of some of the `IMPLEMENTATION_UNUSED_SEGMENT_PRESENT` errors. The schema parser should detect the different order when reading the `<implementation>` and throw an error then (with details) rather than when reading the EDI data.

**Comment by nsharma-bh** [comment]
@MikeEdgar So I changed my XML to this and I actually got 2310A and 2310B. I changed 2300 to this
`
<loop code="2300" type="L0004" title="2300">
            <sequence>
              <segment type="CLM"/>
              <segment type="DTP" maxOccurs="150"/>
              <segment type="PWK" maxOccurs="10"/>
              <segment type="CN1"/>
              <segment type="AMT" maxOccurs="40"/>
              <segment type="REF" maxOccurs="30"/>
              <segment type="K3" maxOccurs="10"/>
              <segment type="NTE" maxOccurs="20"/>
              <segment type="CR1"/>
              <segment type="CR2"/>
              <segment type="CRC" maxOccurs="100"/>
              <segment type="HI" maxOccurs="25"/>
              <segment type="HCP"/>

              <loop code="2310A" type="L0006" title="2310A" discriminator="1">
                <sequence>
                  <segment type="NM1" title="identifier">
                    <sequence>
                      <element position="1">
                        <enumeration>
                          <value>DN</value>
                        </enumeration>
                      </element>
                      <element position="2">
                        <enumeration>
                          <value>1</value>
                        </enumeration>
                      </element>
                      <element position="3"/>
                      <element position="4"/>
                      <element position="5"/>
                      <element position="6"/>
                      <element position="7"/>
                      <element position="8"/>
                      <element position="9"/>
                    </sequence>
                  </segment>
                  <segment type="REF"/>
                  <segment type="PRV"/>
                </sequence>
              </loop>

              <loop type="L0006" code="2310B" discriminator="1" title="2310B">
                <sequence>
                  <segment type="NM1">
                    <sequence>
                      <element position="1">
                        <enumeration>
                          <value>82</value>
                        </enumeration>
                      </element>
                      <element position="2">
                        <enumeration>
                          <value>1</value>
                        </enumeration>
                      </element>
                      <element position="3"/>
                      <element position="4"/>
                      <element position="5"/>
                      <element position="6"/>
                      <element position="7"/>
                      <element position="8"/>
                      <element position="9"/>
                    </sequence>
                  </segment>
                  <segment type="REF"/>
                </sequence>
              </loop>

              <loop type="L0007" code="2320" title="Other Subscriber Info (2320)">
                <sequence>
                  <segment type="SBR"/>
                  <segment type="OI"/>
                  <segment type="CAS"/>
                  <segment type="AMT"/>
                  <segment type="MIA"/>
                  <segment type="MOA"/>
                </sequence>
              </loop>

            </sequence>
          </loop>`
But now I'm getting this error
`
Exception in thread "main" java.lang.ClassCastException: io.xlate.edi.internal.schema.StructureType cannot be cast to io.xlate.edi.schema.EDISimpleType
	at io.xlate.edi.internal.stream.validation.UsageNode.getSimpleType(UsageNode.java:145)
	at io.xlate.edi.internal.stream.validation.UsageNode.validate(UsageNode.java:149)
	at io.xlate.edi.internal.stream.validation.Validator.validateElementValue(Validator.java:1152)
	at io.xlate.edi.internal.stream.validation.Validator.validateVersionConstraints(Validator.java:1124)
	at io.xlate.edi.internal.stream.tokenization.ProxyEventHandler.segmentEnd(ProxyEventHandler.java:299)
	at io.xlate.edi.internal.stream.tokenization.Lexer.lambda$new$3(Lexer.java:112)
	at io.xlate.edi.internal.stream.tokenization.Lexer.nextEvent(Lexer.java:503)
	at io.xlate.edi.internal.stream.tokenization.Lexer.parse(Lexer.java:273)
	at io.xlate.edi.internal.stream.StaEDIStreamReader.nextEvent(StaEDIStreamReader.java:171)
	at io.xlate.edi.internal.stream.StaEDIStreamReader.next(StaEDIStreamReader.java:203)
	at org.example.EDIParser$.delayedEndpoint$org$example$EDIParser$1(EDIParser.scala:23)
	at org.example.EDIParser$delayedInit$body.apply(EDIParser.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.example.EDIParser$.main(EDIParser.scala:9)
	at org.example.EDIParser.main(EDIParser.scala)
`
Am I still doing something wrong ? I was not expecting this error to occur again

**Comment by MikeEdgar** [comment]
I was able to reproduce that error also and I'll provide a fix. You can work around it by adding the other 2310 loop types.

**Comment by nsharma-bh** [comment]
Okay so you mean 2310C and 2310D and 2320 which are other subscriber loops also ??
