### ISSUE TITLE
URI is not absolute Exception

### ISSUE THREAD

**Issue by MikeEdgar** [xlate/staedi#57]
Exception in thread "main" java.lang.IllegalArgumentException: URI is not absolute
at java.net.URI.toURL(Unknown Source)
at io.xlate.edi.internal.schema.SchemaUtils.getXmlSchema(SchemaUtils.java:117)
at io.xlate.edi.internal.schema.SchemaUtils.getControlSchema(SchemaUtils.java:94)
at io.xlate.edi.internal.stream.StaEDIStreamReader.nextEvent(StaEDIStreamReader.java:130)
at io.xlate.edi.internal.stream.StaEDIStreamReader.next(StaEDIStreamReader.java:179)

**Comment by MikeEdgar** [comment]
Please do not use version 1.8.0 due to this bug.
